fun main()
{
    var cinema=Cinema("", 0.0,0.0,0,0)
    cinema.SetInfo()
    cinema.Skidka()
    cinema.GetInfo()
    var cinema_grin=Cinema_Grin(0.0,0,0.0,"",0.0,0.0,0,0)
    println("Зал Гринвич")
    cinema_grin.SetNazv()
    cinema_grin.GetInfo()
    cinema_grin.Zena()
    cinema_grin.Skid()
    var  cinema_pass=Cinema_Pass(0.0,0,0.0,"",0.0,0.0,0,0)
    println("Зал Пассаж")
    cinema_pass.SetNazv()
    cinema_pass.GetInfo()
    cinema_pass.Zena()
    cinema_pass.Skid()
}